[package]
name = "bookworm"
authors.workspace = true
version.workspace = true
edition.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
name = "bookworm"
path = "src/bin/main.rs"

[lib]
name = "bookworm"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["std", "derive", "env"] }
lopdf = { workspace = true }
memmap2 = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
xml-rs = { workspace = true }
zip = { workspace = true, features = ["default"] }

[target.wasm32-unknown-unknown.dependencies]
lopdf = { workspace = true, features = ["wasm_js"] }
getrandom = { workspace = true, features = ["wasm_js"] }
zip = { workspace = true }
